**Q9b. An Ad- Agency analyzed a dataset of online ads and used a machine learning
model to predict whether a user would click on an ad or not.
Dataset This is the Dataset You can use this dataset for this question.**

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv("ad.csv")

In [3]:
df.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000010e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000020e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000040e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000060e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000070e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                5000 non-null   float64
 1   click             5000 non-null   int64
 2   hour              5000 non-null   int64
 3   C1                5000 non-null   int64
 4   banner_pos        5000 non-null   int64
 5   site_id           5000 non-null   object
 6   site_domain       5000 non-null   object
 7   site_category     5000 non-null   object
 8   app_id            5000 non-null   object
 9   app_domain        5000 non-null   object
 10  app_category      5000 non-null   object
 11  device_id         5000 non-null   object
 12  device_ip         5000 non-null   object
 13  device_model      5000 non-null   object
 14  device_type       5000 non-null   int64
 15  device_conn_type  5000 non-null   int64
 16  C14               5000 non-null   int64
 17  C15               5000 non-null   int64
 18  C16               5000 non-null   int64
 19  C17               5000 non-null   int64
 20  C18               5000 non-null   int64
 21  C19               5000 non-null   int64
 22  C20               5000 non-null   int64
 23  C21               5000 non-null   int64
dtypes: float64(1), int64(14), object(9)
memory usage: 937.6+ KB

In [5]:
df.nunique()

id                  3756
click                  2
hour                   1
C1                     5
banner_pos             3
site_id              276
site_domain          234
site_category         14
app_id               210
app_domain            22
app_category          10
device_id            574
device_ip           4016
device_model         841
device_type            4
device_conn_type       4
C14                  216
C15                    4
C16                    5
C17                  104
C18                    4
C19                   32
C20                   91
C21                   28
dtype: int64

In [6]:
df.shape

(5000, 24)

In [7]:
df.isnull().sum()

id                  0
click               0
hour                0
C1                  0
banner_pos          0
site_id             0
site_domain         0
site_category       0
app_id              0
app_domain          0
app_category        0
device_id           0
device_ip           0
device_model        0
device_type         0
device_conn_type    0
C14                 0
C15                 0
C16                 0
C17                 0
C18                 0
C19                 0
C20                 0
C21                 0
dtype: int64

In [8]:
num_f = []
cat_f = []
for i in df.columns:
    if df[i].dtypes == 'object':
        cat_f.append(i)
    else:
        num_f.append(i)
print(num_f)
print(cat_f)

['id', 'click', 'hour', 'C1', 'banner_pos', 'device_type', 'device_conn_type', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21']
['site_id', 'site_domain', 'site_category', 'app_id', 'app_domain', 'app_category', 'device_id', 'device_ip', 'device_model']

In [9]:
from sklearn.preprocessing import LabelEncoder

for i in cat_f:
    encoder = LabelEncoder()
    df[i] = encoder.fit_transform(df[i])

In [10]:
df

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000010e+18,0,14102100,1005,0,31,221,2,196,9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000020e+19,0,14102100,1005,0,31,221,2,196,9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000040e+19,0,14102100,1005,0,31,221,2,196,9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000060e+19,0,14102100,1005,0,31,221,2,196,9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000070e+19,0,14102100,1005,1,271,130,0,196,9,...,1,0,18993,320,50,2161,0,35,-1,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1.070270e+19,0,14102100,1005,0,149,187,5,145,15,...,1,0,1276,320,50,196,3,303,100075,15
4996,1.070320e+19,0,14102100,1005,1,271,130,0,196,9,...,1,0,20596,320,50,2161,0,35,-1,157
4997,1.070330e+18,1,14102100,1005,1,222,180,3,196,9,...,1,0,20596,320,50,2161,0,35,-1,157
4998,1.070340e+19,0,14102100,1005,0,31,221,2,196,9,...,1,0,15708,320,50,1722,0,35,-1,79
4999,1.070340e+19,0,14102100,1002,0,236,76,5,196,9,...,0,0,20352,320,50,2333,0,39,-1,157

In [11]:
X = df.drop('click', axis=1)
y = df['click']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
from sklearn.metrics import classification_report

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt_pred = dt.predict(X_test)
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       820
           1       0.24      0.23      0.24       180

    accuracy                           0.73      1000
   macro avg       0.54      0.54      0.54      1000
weighted avg       0.73      0.73      0.73      1000

In [35]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr_pred = lr.predict(X_test)
print(classification_report(y_test,lr_pred))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90       820
           1       0.00      0.00      0.00       180

    accuracy                           0.82      1000
   macro avg       0.41      0.50      0.45      1000
weighted avg       0.67      0.82      0.74      1000

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89       820
           1       0.36      0.08      0.14       180

    accuracy                           0.81      1000
   macro avg       0.59      0.53      0.51      1000
weighted avg       0.74      0.81      0.76      1000

In [36]:
from sklearn.svm import SVC
svm_clf = SVC()
svm_clf.fit(X_train, y_train)
svm_pred = svm_clf.predict(X_test)
print(classification_report(y_test,svm_pred))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90       820
           1       0.00      0.00      0.00       180

    accuracy                           0.82      1000
   macro avg       0.41      0.50      0.45      1000
weighted avg       0.67      0.82      0.74      1000

In [14]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier()
xgb_clf.fit(X_train,y_train)
xgb_pred = xgb_clf.predict(X_test)
print(classification_report(y_test,xgb_pred))

              precision    recall  f1-score   support

           0       0.83      0.94      0.88       820
           1       0.30      0.11      0.16       180

    accuracy                           0.79      1000
   macro avg       0.57      0.53      0.52      1000
weighted avg       0.73      0.79      0.75      1000